### ISSUE TITLE
Doubt with hierarchical GP's prediction

### ISSUE THREAD

**Issue by juangil** [SheffieldML/notebook#9]
@lawrennd @mzwiessele @jameshensman  I was making a little experiment with hierarchical Gp's in which i generate the replicates similar to the method used in the first part of the hierarchical notebook(https://github.com/SheffieldML/notebook/blob/master/compbio/Hierarchical.ipynb), then what i did was to construct a GP hierarchical model as suggested in the notebook. After the model optimization i wanted to compute the posterior(predict) over the underlying trend given the observed replicates. Although i realized that the mean of the posterior was very similar to the common trend used to generate the data, the full posterior covariance of the underlying trend was not that similar. Thus, maybe am i making some mistake? or maybe i'm misleading myself thinking that is possible to recover the covariance structure of the underlying trend from the replicates. Thanks in advance.
my notebook:
https://github.com/juangil/machine_learning_class/blob/master/GP_tests/mocap_test_1/HGP_Tests.ipynb

**Comment by lawrennd** [comment]
Hi Juan,

The link you provide to your notebook is the localhost link, not a
publically available one.

Neil

**Comment by juangil** [comment]
I think i already corrected the link. Sorry for the inconvenient

**Comment by lawrennd** [comment]
Do I understand correctly that you only have one parent signal? In that
case it probably is not too surprising if you don't get a fully accurate
recovery of its covariance (are you saying prior covariance here?). Because
there might be some ambiguity between the parent and some of the children.
Does it fix it if you increase the number of children greatly?

I've only had a brief look through but can't see anything immediately
that's obviously wrong.

Neil

**Comment by juangil** [comment]
Yes, I have only one parent signal sampled from a GP to use it as the mean to generate the observed samples. The covariance of that parent signal is the one i wish to recover, assuming the parent is unknown.  Although i tried to increment the amount of child signals(to 50) as you suggested, the covariance wasn't recovered as expected. In fact, the recovered covariance is more similar to the children covariance used to generate the observed samples. This is clearly "wrong" because i'm trying to predict the parent. In the final part of my notebook i compare both the recovered covariance from observed data and the one used to generate the data.
So you are suggesting i must use several parent singals?, because after this i want to apply the model to a data set with not enough "children".

**Comment by jameshensman** [comment]
I assume we're looking at this: https://github.com/juangil/machine_learning_class/blob/master/GP_tests/mocap_test_1/HGP_Tests.ipynb

cell out[107]?

If so, I think the error-bars are too high because model.predict is adding in the noise variance. perhaps try `model._raw_predict(...)` instead.

**Comment by juangil** [comment]
@jameshensman  Yes that's the notebook but it's not what i wanted to check, the cell that you mention is a test made with deeper hierarchies, and indeed using _raw_predict decreases the error bars, thanks. However, I'm more interested in the result of: 
cell Out[75]
cell Out[78]
In which i'm trying to reconstruct the original parent signal and the covariance matrix used to generate that signal respectively. Although i tried different things i have not been capable of recovering the covariance correctly.
The result in cell Out[78] shows three covariances:
1. The one predicted by the model(using model.predict) for the upper layer.
2. The real covariance matrix used to generate the parent signal of the upper layer.
3. The covariance computed with the estimated parameters after applying model.optimize.

I expected the first one and the second one to be similar, given the fact i'm predicting the parent signal conditioned to the observed child signals but that's not happening. Maybe i'm misinterpreting the hierarchical model in some way?

**Comment by jameshensman** [comment]
Okay, I've had a read through, and I think there's a misunderstanding somewhere. 

in Out[78]
1. is a *posterior* covariance over the function
2. is the real prior covariance of the function
3. is a 'prior' covariance but using estimated parameters. 

So, if the ML estimate of the parameters is good, then 2. should look like 3 (it does). But 1. should only look like 2 (or 3) if there are no data. In fact, you can see this by giving them all the same color scale:

```python
mtmp = k1.K(inp, None)
plt.figure(1, figsize=(15,6))

plt.subplot(1,4,1)
plt.title('parent covariance posterior')
plt.imshow(mvar, vmin=0, vmax=1)

plt.subplot(1,4,2)
plt.title('Prior parent covariance')
plt.imshow(C_parent_gen, vmin=0, vmax=1)

plt.subplot(1,4,3)
plt.title('Prior parent covariance using estimated parameters')
plt.imshow(mtmp, vmin=0, vmax=1)
```

in this case, you can see that the posterior variance (and co-variance) is reduced relative to the prior covariance, as you'd expect. 

I hope that's made things a bit clearer,
J.

**Comment by juangil** [comment]
@jameshensman Thanks a lot for taking the time of reviewing my notebook. 
1. I already pushed the results using the changes you suggested. but i don't understand why the posterior covariance is whole of the same blue color(Out[109]), i tested it several times.
2. Evidently if you estimate similar parameters from the optimization then 2 and 3 have to be the same.
3. I thought that computing the posterior for the underlying trend conditioned to data would give the prior covariance used to generate the data in the first place. The thing is that i had the idea that the data had to encode in some way the estructure of the parent covariance which was generated from, and in fact that's true i think, but if i understood you well, to compute that parent prior covariance one only needs the parameters estimated by the model optimization process. Because what i want to do after this is to generate samples from the learned model but for other data set.
4. Correct me if i'm not right but maybe the reason for the posterior covariance to not be the same as the prior parent covariance it's that when i condition the posterior to observed data(replicates) i'm computing a distribution for the parent function, and that parent function is only one of all the possible other parent functions which can be sampled from the original distribution with zero mean.

**Comment by jameshensman** [comment]
1) Because the posterior variance is small. The graph is all blue because
it's on the same color scale at the others.
2) Yep.
3) I think the problem is that you're conflating the covariance of the
model, covariance of the data,  and the covariance of the posterior.
They're all different!
a) The covariance of the model is a property of the prior distribution.
(I've also called this the prior covariance)
b) The (empirical) covariance of the data is a property of the sample drawn
from the model. With enough independent samples, it will consistently
estimate the model (prior) covariance.
c) is a property of the posterior distribution.
4) "posterior covariance to not be the same as the prior parent
covariance". As above, these are properties of the prior and posterior
distributions, so they would only be the same if the prior and posterior
distributions were the same (assuming they're both Gaussian, which is true
in this case).

I hope this is helpful. You might be comforted to hear that I'm confident
that GPy is working correctly here! I think you're very close
to understanding what's going on.

There's loads of help on this kind of stuff at the GPSS! http://gpss.cc

James.

**Comment by juangil** [comment]
@jameshensman Thanks a lot for the help, i'll keep working and i hope to find the results i expect very soon.
Juan.
